name: Lacework 
description: Find vulnerabilities and misconfigurations in your builds early in the development process.
author: https://github.com/erikwennerberg
requirements:
  - lacework
  - docker
configuration:
  properties:
    scan-type:
        enum: [ "sca", "iac", "vulnerability","sast" ]
    iac-scan-type:
        enum: [ "cloudformation-scan", "kubernetes-scan", "helm-scan","terraform-scan","kustomize-scan","secrets-scan" ]
    vulnerability-scan-repository:
      type: string
    vulnerability-scan-tag:
      type: string
    fail-level:
      enum: [ "critical", "high", "medium","low","info" ]
    account-name:
      type: string
    api-key-env-var:
      type: string
    api-key-secret-env-var:
      type: string
    access-token-env-var:
      type: string
    profile:
      type: string
  required:
    - account-name
    - scan-type
  additionalProperties: false