name: Lacework
description: Secure your cloud from build to run and respond effectively with risk and threat insights
author: https://github.com/buildkite-plugins
requirements:
  - lacework
configuration:
  properties:
    account-name:
      type: string
    api-key-env-var:
      type: string
    api-key-secret-env-var:
      type: string
    profile:
      type: string
  required:
    - account-name
  additionalProperties: false